name: Go
on: [push, pull_request]
jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.10
        uses: actions/setup-go@v1
        with:
          go-version: 1.10
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: go build ./...
      - name: Test
        run: |
          go mod tidy -v
          go test -race ./...
